POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhbGxvRGFhciIsImlkIjoiNjYyOGU0ZGI4NDBjNTZiZjkzZTgxZjhjIiwiaWF0IjoxNzEzOTY2MTQ1LCJleHAiOjE3MTM5Njk3NDV9.mHiKluucdv12Lssb-K5Ht2lFcmVwWKcwtekN4sQ0Y9A

{
    "title": "Speak Fool",
    "author": "Arthas Menethil",
    "url": "www.kj.com",
    "likes": 9,
    "user": "6628e4db840c56bf93e81f8c"
}