POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer x

{
    "title": "Speak Fool",
    "author": "Arthas Menethil",
    "url": "www.kj.com",
    "likes": 9,
    "user": "6628e4db840c56bf93e81f8c"
}