Put http://localhost:3003/api/blogs/662a49625f1efa3296b00c92 HTTP/1.1
Content-Type: application/json
Authorization: Bearer x

{
    "title": "EenTitel",
    "author": "Arthas Menethil",
    "url": "www.am.com",
    "likes": 1,
    "user": "6628e4db840c56bf93e81f8c"
}